---
name: prom-stack

services:
  grafana:
    image: grafana/grafana:11.3.0
    restart: unless-stopped
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
      - grafana_log:/var/log/grafana
      - grafana_provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - renderer

  renderer:
    image: grafana/grafana-image-renderer:latest
    restart: unless-stopped

  webhookbot:
    image: atompi/webhookbot:v1.1.0
    restart: unless-stopped
    volumes:
      - ./conf/webhookbot/webhookbot.yaml:/app/webhookbot.yaml
      - ./conf/webhookbot/tmpl:/app/tmpl

  webhook-tester:
    image: tarampampam/webhook-tester:1.1.0
    restart: unless-stopped
    command: serve --port 8080 --create-session 00000000-0000-0000-0000-000000000000
    ports:
      - 8080:8080

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.25.0
    restart: unless-stopped
    command:
      - --config.file=/config/blackbox.yaml
    volumes:
      - ./conf/blackbox:/config

  vmstorage-1:
    image: victoriametrics/vmstorage:v1.106.1-cluster
    restart: unless-stopped
    volumes:
      - vmstorage-1_data:/storage
    command:
      - --storageDataPath=/storage
      - --retentionPeriod=6

  vmstorage-2:
    image: victoriametrics/vmstorage:v1.106.1-cluster
    restart: unless-stopped
    volumes:
      - vmstorage-2_data:/storage
    command:
      - --storageDataPath=/storage
      - --retentionPeriod=6

  vmstorage-3:
    image: victoriametrics/vmstorage:v1.106.1-cluster
    restart: unless-stopped
    volumes:
      - vmstorage-3_data:/storage
    command:
      - --storageDataPath=/storage
      - --retentionPeriod=6

  vminsert:
    image: victoriametrics/vminsert:v1.106.1-cluster
    restart: unless-stopped
    depends_on:
      - vmstorage-1
      - vmstorage-2
      - vmstorage-3
    command:
      - --storageNode=vmstorage-1:8400
      - --storageNode=vmstorage-2:8400
      - --storageNode=vmstorage-3:8400
    ports:
      - 8480:8480

  vmselect:
    image: victoriametrics/vmselect:v1.106.1-cluster
    restart: unless-stopped
    depends_on:
      - vmstorage-1
      - vmstorage-2
      - vmstorage-3
    command:
      - --storageNode=vmstorage-1:8401
      - --storageNode=vmstorage-2:8401
      - --storageNode=vmstorage-3:8401
    ports:
      - 8481:8481

  vmagent:
    image: victoriametrics/vmagent:v1.106.1
    restart: unless-stopped
    depends_on:
      - vminsert
    ports:
      - 8429:8429
    volumes:
      - ./conf/prometheus:/etc/prometheus
      - vmagent_data:/vmagent-remotewrite-data
    command:
      - --promscrape.config=/etc/prometheus/vmagent.yaml
      - --promscrape.fileSDCheckInterval=60s
      - --remoteWrite.url=http://vminsert:8480/insert/multitenant/prometheus/
      - --remoteWrite.maxDiskUsagePerURL=1GB

  vmalert:
    image: victoriametrics/vmalert:v1.106.1
    restart: unless-stopped
    ports:
      - 8880:8880
    volumes:
      - ./conf/vmalert/rules:/etc/alerts
    command:
      - --datasource.url=http://vmselect:8481/select/multitenant/prometheus
      - --remoteRead.url=http://vmselect:8481/select/multitenant/prometheus
      - --remoteWrite.url=http://vminsert:8480/insert/multitenant/prometheus
      - --notifier.url=http://alertmanager:9093/
      - --rule=/etc/alerts/**/*.yaml
      - --external.url=https://mon.atompi.cc
      - --external.alert.source=explore?orgId=1&left={"datasource":"VictoriaMetrics - cluster","queries":[{"expr":{{.Expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"{{ .ActiveAt.UnixMilli }}","to":"now"}}

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.27.0
    restart: unless-stopped
    volumes:
      - ./conf/alertmanager/alertmanager.yaml:/config/alertmanager.yaml
    command:
      - "--config.file=/config/alertmanager.yaml"

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/grafana/data
  grafana_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/grafana/log
  grafana_provisioning:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/grafana/provisioning
  vmstorage-1_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/victoriametrics/vmstorage1
  vmstorage-2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/victoriametrics/vmstorage2
  vmstorage-3_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/victoriametrics/vmstorage3
  vmagent_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/victoriametrics/vmagent

networks:
  default:
    external: true
    name: compose
