global:
  evaluation_interval: 15s
  scrape_interval: 15s
storage:
  tsdb:
    out_of_order_time_window: 0s
scrape_configs:
- job_name: budget
  scrape_interval: 60m
  file_sd_configs:
    - refresh_interval: 50m
      files:
      - /etc/prometheus/file_sd_configs/budget.yaml
