global:
  scrape_interval: 15s

scrape_configs:
  - job_name: probe_http_2xx
    scrape_interval: 15s
    metrics_path: probe
    params:
      module:
      - http_2xx
    file_sd_configs:
    - files:
      - /etc/prometheus/file_sd_configs/probe_http_2xx.yaml
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115

  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
        labels:
          vm_account_id: 1
          vm_project_id: 0
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
        labels:
          vm_account_id: 1
          vm_project_id: 0
  - job_name: 'vminsert'
    static_configs:
      - targets: ['vminsert:8480']
        labels:
          vm_account_id: 1
          vm_project_id: 0
  - job_name: 'vmselect'
    static_configs:
      - targets: ['vmselect:8481']
        labels:
          vm_account_id: 1
          vm_project_id: 0
  - job_name: 'vmstorage'
    static_configs:
      - targets: ['vmstorage-1:8482', 'vmstorage-2:8482', 'vmstorage-3:8482']
        labels:
          vm_account_id: 1
          vm_project_id: 0

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          cluster: victoriametrics
          namespace: external
          service: victoriametrics-alertmanager
          vm_account_id: 1
          vm_project_id: 1
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          cluster: victoriametrics
          namespace: external
          service: victoriametrics-grafana
          vm_account_id: 1
          vm_project_id: 1
