apiVersion: 1

datasources:
  - name: VictoriaMetrics - cluster
    type: victoriametrics-datasource
    access: proxy
    url: http://vmselect:8481/select/0/prometheus
    isDefault: true
    jsonData:
      vmuiUrl: http://vmselect:8481/select/0/vmui
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://vmselect:8481/select/0/prometheus
    isDefault: false
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.55.0
